/**
 * Mock Nutrition Data
 *
 * Sample data for developing and testing the nutrition page.
 * Represents a typical day with breakfast, lunch, dinner, and snacks.
 */

import type { DailyNutrition } from '../types/nutrition'

export const mockNutritionData: DailyNutrition = {
  date: new Date().toISOString().split('T')[0],
  totalCalories: 1842,
  totalProtein: 142,
  totalCarbs: 185,
  totalFat: 52,
  calorieGoal: 2200,
  proteinGoal: 165,
  carbsGoal: 220,
  fatGoal: 73,
  meals: [
    {
      id: 'meal-1',
      name: 'Morning Fuel',
      mealType: 'breakfast',
      loggedAt: new Date(new Date().setHours(7, 30, 0, 0)).toISOString(),
      totalCalories: 420,
      totalProtein: 32,
      totalCarbs: 48,
      totalFat: 8,
      source: 'manual',
      foodItems: [
        {
          id: 'item-1',
          foodId: 'food-1',
          foodName: 'Greek Yogurt',
          brandName: 'Fage Total 0%',
          quantity: 1,
          servingId: 'serving-1',
          displayUnit: 'cup',
          displayLabel: '227g',
          grams: 227,
          calories: 120,
          protein: 20,
          carbs: 9,
          fat: 0,
          availableServings: [
            {
              id: 'serving-1',
              unit: 'cup',
              label: '1 cup (227g)',
              grams: 227,
              isDefault: true,
            },
            {
              id: 'serving-2',
              unit: 'tbsp',
              label: '1 tbsp (15g)',
              grams: 15,
              isDefault: false,
            },
            {
              id: 'serving-3',
              unit: 'g',
              label: '100g',
              grams: 100,
              isDefault: false,
            },
          ],
        },
        {
          id: 'item-2',
          foodId: 'food-2',
          foodName: 'Blueberries',
          brandName: null,
          quantity: 1,
          servingId: 'serving-4',
          displayUnit: 'cup',
          displayLabel: '148g',
          grams: 148,
          calories: 84,
          protein: 1,
          carbs: 21,
          fat: 0.5,
          availableServings: [
            {
              id: 'serving-4',
              unit: 'cup',
              label: '1 cup (148g)',
              grams: 148,
              isDefault: true,
            },
            {
              id: 'serving-5',
              unit: 'oz',
              label: '1 oz (28g)',
              grams: 28,
              isDefault: false,
            },
          ],
        },
        {
          id: 'item-3',
          foodId: 'food-3',
          foodName: 'Oatmeal',
          brandName: 'Quaker Old Fashioned',
          quantity: 0.5,
          servingId: 'serving-6',
          displayUnit: 'cup',
          displayLabel: '40g dry',
          grams: 40,
          calories: 150,
          protein: 5,
          carbs: 27,
          fat: 3,
          availableServings: [
            {
              id: 'serving-6',
              unit: 'cup',
              label: '1/2 cup dry (40g)',
              grams: 40,
              isDefault: true,
            },
          ],
        },
        {
          id: 'item-4',
          foodId: 'food-4',
          foodName: 'Protein Powder',
          brandName: 'Optimum Nutrition Gold Standard Whey',
          quantity: 1,
          servingId: 'serving-7',
          displayUnit: 'scoop',
          displayLabel: '30g',
          grams: 30,
          calories: 120,
          protein: 24,
          carbs: 3,
          fat: 1.5,
          availableServings: [
            {
              id: 'serving-7',
              unit: 'scoop',
              label: '1 scoop (30g)',
              grams: 30,
              isDefault: true,
            },
          ],
        },
      ],
    },
    {
      id: 'meal-2',
      name: 'Protein Shake',
      mealType: 'snack',
      loggedAt: new Date(new Date().setHours(10, 15, 0, 0)).toISOString(),
      totalCalories: 180,
      totalProtein: 30,
      totalCarbs: 12,
      totalFat: 2,
      source: 'coach_chat',
      aiConfidence: 0.92,
      foodItems: [
        {
          id: 'item-5',
          foodId: 'food-5',
          foodName: 'Banana',
          brandName: null,
          quantity: 1,
          servingId: 'serving-8',
          displayUnit: 'medium',
          displayLabel: '118g',
          grams: 118,
          calories: 105,
          protein: 1.3,
          carbs: 27,
          fat: 0.4,
          availableServings: [
            {
              id: 'serving-8',
              unit: 'medium',
              label: '1 medium (118g)',
              grams: 118,
              isDefault: true,
            },
            {
              id: 'serving-9',
              unit: 'large',
              label: '1 large (136g)',
              grams: 136,
              isDefault: false,
            },
          ],
        },
        {
          id: 'item-6',
          foodId: 'food-4',
          foodName: 'Protein Powder',
          brandName: 'Optimum Nutrition Gold Standard Whey',
          quantity: 0.75,
          servingId: 'serving-7',
          displayUnit: 'scoop',
          displayLabel: '22.5g',
          grams: 22.5,
          calories: 90,
          protein: 18,
          carbs: 2.3,
          fat: 1.1,
          availableServings: [
            {
              id: 'serving-7',
              unit: 'scoop',
              label: '1 scoop (30g)',
              grams: 30,
              isDefault: true,
            },
          ],
        },
      ],
    },
    {
      id: 'meal-3',
      name: 'Grilled Chicken Bowl',
      mealType: 'lunch',
      loggedAt: new Date(new Date().setHours(12, 45, 0, 0)).toISOString(),
      totalCalories: 562,
      totalProtein: 45,
      totalCarbs: 58,
      totalFat: 12,
      source: 'ai_photo',
      aiConfidence: 0.87,
      foodItems: [
        {
          id: 'item-7',
          foodId: 'food-6',
          foodName: 'Chicken Breast',
          brandName: null,
          quantity: 6,
          servingId: 'serving-10',
          displayUnit: 'oz',
          displayLabel: '170g',
          grams: 170,
          calories: 280,
          protein: 53,
          carbs: 0,
          fat: 6,
          availableServings: [
            {
              id: 'serving-10',
              unit: 'oz',
              label: '1 oz (28g)',
              grams: 28,
              isDefault: true,
            },
            {
              id: 'serving-11',
              unit: 'breast',
              label: '1 breast (170g)',
              grams: 170,
              isDefault: false,
            },
          ],
        },
        {
          id: 'item-8',
          foodId: 'food-7',
          foodName: 'Brown Rice',
          brandName: null,
          quantity: 1,
          servingId: 'serving-12',
          displayUnit: 'cup',
          displayLabel: '195g cooked',
          grams: 195,
          calories: 218,
          protein: 5,
          carbs: 46,
          fat: 1.6,
          availableServings: [
            {
              id: 'serving-12',
              unit: 'cup',
              label: '1 cup cooked (195g)',
              grams: 195,
              isDefault: true,
            },
          ],
        },
        {
          id: 'item-9',
          foodId: 'food-8',
          foodName: 'Mixed Vegetables',
          brandName: 'Frozen Blend',
          quantity: 1.5,
          servingId: 'serving-13',
          displayUnit: 'cup',
          displayLabel: '120g',
          grams: 120,
          calories: 64,
          protein: 3,
          carbs: 12,
          fat: 0.4,
          availableServings: [
            {
              id: 'serving-13',
              unit: 'cup',
              label: '1 cup (80g)',
              grams: 80,
              isDefault: true,
            },
          ],
        },
      ],
    },
    {
      id: 'meal-4',
      name: 'Afternoon Snack',
      mealType: 'snack',
      loggedAt: new Date(new Date().setHours(15, 30, 0, 0)).toISOString(),
      totalCalories: 220,
      totalProtein: 12,
      totalCarbs: 24,
      totalFat: 8,
      source: 'manual',
      foodItems: [
        {
          id: 'item-10',
          foodId: 'food-9',
          foodName: 'Almonds',
          brandName: null,
          quantity: 1,
          servingId: 'serving-14',
          displayUnit: 'oz',
          displayLabel: '23 nuts',
          grams: 28,
          calories: 164,
          protein: 6,
          carbs: 6,
          fat: 14,
          availableServings: [
            {
              id: 'serving-14',
              unit: 'oz',
              label: '1 oz (28g, ~23 nuts)',
              grams: 28,
              isDefault: true,
            },
            {
              id: 'serving-15',
              unit: 'nut',
              label: '1 almond (~1.2g)',
              grams: 1.2,
              isDefault: false,
            },
          ],
        },
        {
          id: 'item-11',
          foodId: 'food-10',
          foodName: 'Apple',
          brandName: null,
          quantity: 1,
          servingId: 'serving-16',
          displayUnit: 'medium',
          displayLabel: '182g',
          grams: 182,
          calories: 95,
          protein: 0.5,
          carbs: 25,
          fat: 0.3,
          availableServings: [
            {
              id: 'serving-16',
              unit: 'medium',
              label: '1 medium (182g)',
              grams: 182,
              isDefault: true,
            },
            {
              id: 'serving-17',
              unit: 'large',
              label: '1 large (223g)',
              grams: 223,
              isDefault: false,
            },
          ],
        },
      ],
    },
    {
      id: 'meal-5',
      name: 'Salmon Dinner',
      mealType: 'dinner',
      loggedAt: new Date(new Date().setHours(18, 30, 0, 0)).toISOString(),
      totalCalories: 460,
      totalProtein: 40,
      totalCarbs: 43,
      totalFat: 14,
      source: 'ai_text',
      aiConfidence: 0.78,
      foodItems: [
        {
          id: 'item-12',
          foodId: 'food-11',
          foodName: 'Atlantic Salmon',
          brandName: null,
          quantity: 5,
          servingId: 'serving-18',
          displayUnit: 'oz',
          displayLabel: '140g',
          grams: 140,
          calories: 280,
          protein: 39,
          carbs: 0,
          fat: 13,
          availableServings: [
            {
              id: 'serving-18',
              unit: 'oz',
              label: '1 oz (28g)',
              grams: 28,
              isDefault: true,
            },
            {
              id: 'serving-19',
              unit: 'fillet',
              label: '1 fillet (140g)',
              grams: 140,
              isDefault: false,
            },
          ],
        },
        {
          id: 'item-13',
          foodId: 'food-12',
          foodName: 'Sweet Potato',
          brandName: null,
          quantity: 1,
          servingId: 'serving-20',
          displayUnit: 'medium',
          displayLabel: '114g',
          grams: 114,
          calories: 103,
          protein: 2.3,
          carbs: 24,
          fat: 0.2,
          availableServings: [
            {
              id: 'serving-20',
              unit: 'medium',
              label: '1 medium (114g)',
              grams: 114,
              isDefault: true,
            },
            {
              id: 'serving-21',
              unit: 'large',
              label: '1 large (180g)',
              grams: 180,
              isDefault: false,
            },
          ],
        },
        {
          id: 'item-14',
          foodId: 'food-13',
          foodName: 'Asparagus',
          brandName: null,
          quantity: 8,
          servingId: 'serving-22',
          displayUnit: 'spear',
          displayLabel: '112g',
          grams: 112,
          calories: 22,
          protein: 2.4,
          carbs: 4.1,
          fat: 0.2,
          availableServings: [
            {
              id: 'serving-22',
              unit: 'spear',
              label: '1 spear (14g)',
              grams: 14,
              isDefault: true,
            },
            {
              id: 'serving-23',
              unit: 'cup',
              label: '1 cup (134g)',
              grams: 134,
              isDefault: false,
            },
          ],
        },
      ],
    },
  ],
}
